### PR TITLE
fix: add csrf token to event context

### PR DESCRIPTION
**Pull request by outofthisworld**
1. Add nitro request hook.
2. Add CSRF token to event context, making it accessible in pages.

see issue #20

### CODE REVIEW

**Comment by Morgbn** [comment]
Hello @outofthisworld,
thanks for the pull request,
Not sure if it's a good idea to set a cookie at each request. I need to explore this further.
In the meantime, I'm not sure what the point is. Can't you create a minimal reproducible example that demonstrates the problem  this PR solves ?

**Comment by outofthisworld** [comment]
> Hello @outofthisworld, thanks for the pull request, Not sure if it's a good idea to set a cookie at each request. I need to explore this further. In the meantime, I'm not sure what the point is. Can't you create a minimal reproducible example that demonstrates the problem this PR solves ?

Hi @Morgbn,

This doesn't set a cookie on each request. It functions in the exact same way that the original code works however makes the generated csrf token available server side. This means that any SSR requests that need to include a CSRF token can indeed access the generated token.

It is absolutely no different from "render:html" which is also called for every 'request'

**Comment by Morgbn** [comment]
"request" is hit at all request (get, post, ...) while "render:html" only when nitro render an html page...
But you're right, if we want useCsrfFetch(..., { method: **'post'**|**'put'**|**'patch'** }) to be called on server side we need to add the csrfToken in event.context.
I will add an opt-in option for that specific case 👍

**Comment by outofthisworld** [comment]
> "request" is hit at all request (get, post, ...) while "render:html" only when nitro render an html page... But you're right, if we want useCsrfFetch(..., { method: **'post'**|**'put'**|**'patch'** }) to be called on server side we need to add the csrfToken in event.context. I will add an opt-in option for that specific case 👍

Well, I'm sure its possible to check the request method is 'GET' in the request hook. In addition, we can probably check its a page route. 

Regardless apart from the slight extra computation to produce the csrf token from the secret that's stored in the cookie - it doesn't really make much difference and this would still function correctly.

**Comment by Morgbn** [comment]
Thank you @outofthisworld,
it was easier for me to just write a commit (with the option directly and `useCsrf` updated), but I appreciate your contribution !

**Pull request closed without merging**
